name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download NuGet packages
        uses: actions/download-artifact@v8
        with:
          name: NuGets
          path: bin/NuGets/

      - name: Publish NuGet packages to GitHub Packages
        run: |
          dotnet nuget push "bin/NuGets/**/*.nupkg" \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --skip-duplicate

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet packages to NuGet.org
        run: |
          dotnet nuget push "bin/NuGets/**/*.nupkg" \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate